### ISSUE TITLE
moveAccuracy doesn't work

### ISSUE THREAD

**Issue by Godde** [spring/RapidTools#25]
MoveAccuracy doesn't work which should make units innaccurate when firing on the move.
A KingTiger is accurate even on the move currently even at max range.
I have tested really high values for MoveAccuracy to no effect.

**Comment by Godde** [comment]
I tested this with latest git version of s44. I'm not sure if this tag is broken or if it is just broken in Spring 1944.

**Comment by abma** [comment]
what? this is the repo of http://springrts.com/wiki/RapidTools

spring 1944 repo is there:
https://github.com/spring1944/spring1944

**Comment by abma** [comment]
hmm, the "thanks for using rapidtools" link?
