### ISSUE TITLE
RevisionNinja is too verbose

### ISSUE THREAD

**Issue by silentwings** [spring/RapidTools#31]
At the moment it prints far more info than is needed, with more lines and repition than is needed. This can cloud channels - see screenshot.

Part of it is SLs fault, though.

**Comment by silentwings** [comment]
![revn](https://cloud.githubusercontent.com/assets/3885930/9025812/ceaf9992-390d-11e5-9499-2dc07f304b47.png)

**Comment by abma** [comment]
what do you suggest, how to improve?

**Comment by silentwings** [comment]
Remove the "left the channel + link" message for RevisionNinja & remove the request to 'update', in both cases the info is available elsewhere and is not needed there.

**Comment by abma** [comment]
the message isn't for fun there. the exit message requires a change in springlobby

**Comment by abma** [comment]
a small note:

removal of direct svn support doesn't mean rapidtools can't handle svn at all. git itself has a wrapper to handle svn repositories. the code of svn support make it very difficult to use it in other projects, as the dependencies (apr) are difficult to compile on other platforms. the other dependencies are mostly already are available as spring requires them, too.

-> the removal allows integration / merge with spring and/or pr-downloader

**Comment by silentwings** [comment]
That's not relevent to this ticket - and spamming "please don't use svn" messages after you've already spammed thousands is unlikely to change anyones mind. In any case, it's not me you have to convince here. I don't maintain BAs infrastructure and (except for a minor irritation with softlinks) its immaterial to me whether I commit to svn/git repos. I'm just put off reading the channel due to spam.

**Comment by abma** [comment]
http://imolarpg.dyndns.org/trac/balatest/ticket/830 is ignored, why to remove the informal message, that svn is deprecated? is a hard end-date needed for svn support?

**Comment by abma** [comment]
shall i disable the bot for svn?

**Comment by silentwings** [comment]
It's no use threatening me either, I can't change anything here. You should contact Behe (and it would probably be better to do it sooner rather than later, since he has been active the past couple of weeks).

**Comment by abma** [comment]
pm'ed him on the springrts forum...
