### ISSUE TITLE
add dependencies from modinfo.lua into versions.gz

### ISSUE THREAD

**Issue by gajop** [spring/RapidTools#37]
It should be possible to include rapid dependencies, e.g. : 

```
 depend = {
    'rapid://ba:stable',
  },
```

Example file: https://github.com/gajop/Scened-BA/blob/master/modinfo.lua
PS: Haven't tested, but I assume this doesn't work, and nothing in code suggests it would.

**Comment by abma** [comment]
yep, this doesn't work:

BuildGit doesn't parse this info -> there is no info about dependencies in versions.gz.

as pr-downloader doesn't parse modinfo.lua as well depends don't work with pr-downloader/spring atm.

**Comment by abma** [comment]
not sure how to add multiple depends into versions.gz: this seems to basicly not work without changing the format of versions.gz

**Comment by abma** [comment]
thats out of scope for rapidtools.

looks more like https://github.com/springfiles/upq/issues/25 should be implemented
