### ISSUE TITLE
error when updating jw

### ISSUE THREAD

**Issue by abma** [spring/RapidTools#39]
Updateing /home/packages/git/jw
Updating 0aa08fa..837e0b4
Fast-forward
 README.md | 2 ++
 1 file changed, 2 insertions(+)
Already on 'master'
Your branch is up-to-date with 'origin/master'.
HEAD is now at 837e0b4 VERSION{52.3}
Performing incremental update: 9f0fc4d7fefe6e9a08ae578e0a369817638a60fd...837e0b482fd3103fb7deade7eba5111cadc80372
M	EngineOptions.lua
M	LuaRules/Gadgets/jw_ComEnd.lua
M	LuaRules/Gadgets/jw_ProjectileImpacts.lua
D	LuaRules/callins.lua
M	LuaRules/gadgets.lua
A	LuaUI/images/cres_metal copy.png
M	LuaUI/images/jres_energy.png
M	LuaUI/images/jres_metal.png
A	LuaUI/images/jres_metal.psd
A	LuaUI/images/jresenergy.png
M	LuaUI/images/jresenergy.psd
M	LuaUI/widgets/gui_AbilityWindow.lua
A	LuaUI/widgets/gui_AbilityWindow.luad
M	LuaUI/widgets/gui_resbarplus.lua
M	README.md
D	WIP/infolog.txt
M	gamedata/explosions/orangeSmoke.lua
A	libs/chonsole
git_blob_lookup [-3] - Object not found - failed to find pack entry (208a7f71fd42d3eef00151eb08c29549ddd855a3)

**Comment by abma** [comment]
seems https://springrts.com/wiki/RapidTools#BuildGit dislikes submodules :-|

possible removing the submodule workarrounds the bug

**Comment by PicassoCT** [comment]
Deleted the submodule - recommited

**Comment by abma** [comment]
seems to have worked:

http://jw.repo.springrts.com/log.txt
