### ISSUE TITLE
New Rapid tag for Shard LuaAI Core Package is needed

### ISSUE THREAD

**Issue by ForbodingAngel** [spring/RapidTools#40]
https://github.com/eronoobos/ShardSpringLua

Preferred tag(s) would be:
luaai-shard:stable/test

This package will allow gamedevs to add support for Shard LuaAI to their game simply by adding a dependency. Additionally, if this becomes a rapid package, updating to a newer version of the LuaAI is a simple matter of changing the dependency.

**Comment by abma** [comment]
done (will work in a few hours)
