### ISSUE TITLE
New Rapid tag for EvoRTS Shard Config Package is needed

### ISSUE THREAD

**Issue by ForbodingAngel** [spring/RapidTools#41]
https://github.com/EvolutionRTS/Evolution-RTS-Shard-LuaAI

Preferred rapid tag(s) would be (In keeping with the proposed naming convention for the LuaAI core package):
luaai-shard-evorts:stable/test

Purpose:
This allows me completely separate out the LuaAI config files form the game itself and just call them as dependencies. it also allows me to keep the core game repo free of PR's or issues related to AI configs. Additionally, it has the added benefit of allowing me to easily and quickly switch the game between various versions of the configs. The ability is extremely robust and powerful :-)

**Comment by abma** [comment]
done (in a few hours...)
