### ISSUE TITLE
rapid tag for metal factions

### ISSUE THREAD

**Issue by springraaar** [spring/RapidTools#44]
Hi

I've created a github repository for my game, Metal Factions. [](http://metalfactions.pt/)

https://github.com/springraaar/metal_factions

I want my game to be available through rapid.

**Comment by springraaar** [comment]
is there any strict relationship between the tag and the git repository name?

the desired tag name is "metalfactions"

**Comment by springraaar** [comment]
so?

**Comment by abma** [comment]
sorry, vacation + https://springrts.com/phpbb/viewtopic.php?f=71&t=33804

please merge https://github.com/springraaar/metal_factions/pull/1

**Comment by springraaar** [comment]
ok, i did that now

**Comment by springraaar** [comment]
so this means there's already a rapid tag for metal factions? 

I don't see it here:
https://springrts.com/wiki/Rapid_Tags

After I make the first commit with "VERSION{x.xx}" and go to springlobby, tools > download archives : add "game:metalfactions:stable" should work, right?

Is there any potential issue or collision between the springfiles entries I add manually (like [this](https://springfiles.com/spring/games/metal-factions-12)) and the ones rapid adds?

**Comment by abma** [comment]
> Is there any potential issue or collision between the springfiles entries I add manually (like this) and the ones rapid adds?

if you use the same name when manually creating a archive you very likely a desync.
use the builds from rapid after creating a release: http://metalfactions.repo.springrts.com/builds/

for now downloading metalfactions:test works for me. the rapid tags page is manually updated.
