### ISSUE TITLE
Add test and stable tags for Planet-Defense/Planet-Defense to repo

### ISSUE THREAD

**Issue by aronj** [spring/RapidTools#50]
[https://github.com/Planet-Defense/Planet-Defense](https://github.com/Planet-Defense/Planet-Defense)

Tags: 
- pd:stable
- pd:test

It is dependent on Planet Annihilation (currently version 3.9), not sure if that is needed too in that case.

Edit: What I'm asking is: will this work? ;)

I have invited Senna as well to the repo so I hope he will sign up to do stable releases. I will only be doing test releases.

**Comment by abma** [comment]
> Edit: What I'm asking is: will this work? ;)

it should work but its not tested very well, so please report issues.

done, added it to rapid.

**Comment by aronj** [comment]
Many thanks @abma!
