### ISSUE TITLE
Add SpringBoard to rapid

### ISSUE THREAD

**Issue by gajop** [spring/RapidTools#51]
Hello, I've finally made SpringBoard (Scened) free of submodules (and relatively small), so it can be added to rapid.
Can you please add the following to rapid:

sbc : https://github.com/Spring-SpringBoard/SpringBoard-Core
sb-ba : https://github.com/Spring-SpringBoard/SpringBoard-BA
sb-zk : https://github.com/Spring-SpringBoard/SpringBoard-ZK
sb-evo : https://github.com/Spring-SpringBoard/SpringBoard-EVO

PS: I guess #30 would be nice to do so we can properly download dependencies.. (Maybe I should take a look, what needs doing?)

**Comment by abma** [comment]
done, added it to rapid.

**Comment by gajop** [comment]
Thanks!
