### ISSUE TITLE
Add to rapid: Gravitas, ZeusVsBunnies, Flove, PartsNeeded

### ISSUE THREAD

**Issue by gajop** [spring/RapidTools#55]
Please add the following repos to rapid.

rapid-tag: git url

gravitas: https://github.com/SpringCabal/Gravitas.git
zeus-vs-bunnies: https://github.com/SpringCabal/Hunted.git
flove: https://github.com/SpringCabal/Flove.git
parts-needed: https://github.com/SpringCabal/LD35.git

**Comment by abma** [comment]
see https://github.com/SpringCabal/Gravitas/issues/85

**Comment by gajop** [comment]
Fixed Gravitas. The rest seem fine.
Btw, is it possible to add/remove submodules later without any fears? I think I'd like to move more libs to submodules to reduce maintenance work.

**Comment by abma** [comment]
removing a submodule very likely will cause issues, adding it should work without any trouble.

**Comment by gajop** [comment]
Ok, understood. I suppose we can experiment with that in the future and see how robust it is.

**Comment by abma** [comment]
modinfo.lua needs to be lower case: this seems to be wrong in all repos.

**Comment by abma** [comment]
also version needs to be $VERSION

**Comment by gajop** [comment]
`modinfo.lua needs to be lower case` - seems to me like a RapidTools limitation. Spring doesn't mind existing modinfo filenames.
Will fix but should open an issue.

**Comment by abma** [comment]
no, missing feature :-P

spring lowercases all filenames in VFS...

**Comment by gajop** [comment]
Yes but users don't really see that. As far as they're concerned, modinfo.lua (and similar files) can be written in a case insensitive way. RapidTools should accept the same format as Spring does.

Anyway, fixed all the filenames and versions now!

**Comment by abma** [comment]
done!

**Comment by gajop** [comment]
Great, thanks!
