### ISSUE TITLE
JW repository seems not to update

### ISSUE THREAD

**Issue by PicassoCT** [spring/RapidTools#59]
Hi,
i have the version structure in place - as described here : https://springrts.com/wiki/Rapid#Creating_a_release

But if i try to download game:jw:stable, my springlobby is loading for half a eternety and then not presenting me with the corresponding options.

I tryied deleting all the files in the pool. And redownload the game:jw:stable
The version it show is 52.3.
My current version is 134.
https://github.com/PicassoCT/Journeywar 
The only branch active is develop.
https://bitbucket.org/PicassoCT/journeywar/branches/
Again only active branch after the cleanup is develop.

Please contact me if i can do anything to remedy the situation.

PS: I am aware that my game is kind of "fat" compared to other games. If im expected to contribute to the servers bandwith financial wise, please again - contact me.

**Comment by abma** [comment]
log from last commit looks fine: http://jw.repo.springrts.com/log.txt

from http://jw.repo.springrts.com/versions.gz
jw:stable,bb4e0972675a56884283de50daa55f8f,,Journeywar 53.2

looks fine, too. so server-side it seems ok.

do you get an error message when downloading jw? does it say "download complete"?

springlobby.log very likely contains useful info...

**Comment by PicassoCT** [comment]
From the log:

>Already on 'master'
>Your branch is up-to-date with 'origin/master'.
>HEAD is now at 7741695 Version{121.0}

Branch master does not exist.. only develop. Newest Version is 134.

I do not get a error message. I add game:stable:jw - the download moves on - and i can play with 53.2.

It seems to either have lost track of the repo in total or the development branch.

[springlobby.log](https://github.com/spring/RapidTools/files/2442608/springlobby.log)

**Comment by abma** [comment]
rapid doesn't support other branches then "master"...

https://github.com/spring/pr-downloader/blob/master/scripts/update.sh#L33

rename back to master and it will update again.

**Comment by abma** [comment]
see #28

**Comment by PicassoCT** [comment]
I pushed a branch - master. It still doesent seem to update from that.

**Comment by abma** [comment]
ugh:

==30640==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 52 byte(s) in 1 object(s) allocated from:
    #0 0x7f9a32976602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x4243a8 in git__malloc /home/packages/pr-downloader/src/lib/libgit2/src/util.h:29
    #2 0x4243a8 in git_tree_entry_dup /home/packages/pr-downloader/src/lib/libgit2/src/tree.c:216

SUMMARY: AddressSanitizer: 52 byte(s) leaked in 1 allocation(s).


rebuilt without sanitizer.

but this seems to be not the cause. from the docs:

"When the git repository is connected to rapid, a release can be made by making a git-commit with a commit message in the format:

VERSION{x.xx}"

very likely its case sensitive:

https://github.com/spring/pr-downloader/blob/master/src/BuildGit.cpp#L96

**Comment by PicassoCT** [comment]
Seems to be that way. Memory leak is propably my games fault - it has been eating unhealthy.

So, this is still broken. 
I added master branches to both my repos.
I added the correct VERSION commit- i checked to make it as similar to the last one working i could find.
The log and the info file do not seem to update. Which repository are the exactly watching?

**Comment by PicassoCT** [comment]
I think i found it. 
This is watching my atlassian bitbucket repo, for a branch named master.  And that repo did not have one, even though i pushed.
It works now. 
Thanks for all the patience.

**Comment by abma** [comment]
shall i change the update url where rapid fetches to github?

**Comment by PicassoCT** [comment]
It would be great if it points to the master on the github repo. Thanks. Atlassian is somewhat slow in every aspect.

**Comment by abma** [comment]
done.

also now more info is shown in the log after an update:

http://jw.repo.springrts.com/log.txt
