### ISSUE TITLE
rapid request

### ISSUE THREAD

**Issue by ShoX1988** [spring/RapidTools#60]
aa:stable
aa:test
 https://github.com/ShoX1988/Absolut-Annihilation/commits/master

**Comment by silentwings** [comment]
imo there is good reason to get this set up (hosts already exist)

**Comment by silentwings** [comment]
@abma there are people wanting to work on this - a group of ba players & devs wanting to test a fork that preserves more of the "classic" BA - but they can't make much progress until its on rapid

**Comment by abma** [comment]
done: 
http://aa.repo.springrts.com/

**Comment by abma** [comment]
sorry for the delay

**Comment by silentwings** [comment]
thank you :)
