### ISSUE TITLE
Mosaic Repo

### ISSUE THREAD

**Issue by PicassoCT** [spring/RapidTools#61]
Would you kindly at the mosaic repository - the master branch to the rapid system? https://github.com/PicassoCT/mosaic

**Comment by abma** [comment]
"at" vs "add" ;-)

"report the location of your git repository and the wanted rapid tag"

-> whats your wanted tag?

"mosaic" ?

**Comment by PicassoCT** [comment]
mosaic is good

**Comment by abma** [comment]
done!
