### ISSUE TITLE
Please add tchobby to rapid

### ISSUE THREAD

**Issue by azaremoth** [spring/RapidTools#62]
Rapid tag: 
tchobby

Git Folder:
https://github.com/azaremoth/tchobby

**Comment by ashdnazg** [comment]
what does the t stand for?

**Comment by azaremoth** [comment]
It is a fusion of tc (the cursed) and Chobby. 

tc + chobby = tchobby

I did also think about curbby... 😊

KR,
Jan

**Comment by abma** [comment]
done: https://springrts.com/phpbb/viewtopic.php?f=71&t=39165

sorry for making you guinea pig :see_no_evil:
