### ISSUE TITLE
Error with SA:test

### ISSUE THREAD

**Issue by skymyj** [spring/RapidTools#67]
Hey. 
I have this error :  [Error] ../../tools/pr-downloader/src/main.cpp:185:main():No game found for sa:test
Thanks.

**Comment by abma** [comment]
very likely you're using an older version of pr-downloader which caches repos.springrts.com/repos.gz longer as it should

**Comment by abma** [comment]
for now, just delete ~/.spring/rapid/repos.springrts.com/repos.gz to make pr-downloader find the repo.

**Comment by abma** [comment]
thanks for reporting! :)
