### ISSUE TITLE
Add TA Prime to rapid

### ISSUE THREAD

**Issue by MaDDoXbr** [spring/RapidTools#69]
Hi Abma,

Please add https://github.com/FluidPlay/TAPrime

After two years of development and tests, TA Prime is ready to go live - new site and all! (https://www.fluidplay.co/taprime.html). I'll make it public as soon as this is on rapid.

Game's name is "TA Prime", short name is "TAP", I'd like the usual tags:
**tap:test
tap:stable**

Thanks in advance,
MaDDoX

**Comment by abma** [comment]
done!
