### ISSUE TITLE
Add TAP-Chobby to rapid 

### ISSUE THREAD

**Issue by MaDDoXbr** [spring/RapidTools#70]
Hi Abma,

Please add **https://github.com/FluidPlay/TAP-Chobby** to Spring-Rapid, as Gajop requested to me.
I'd like the tags:

tap-chobby:test
tap-chobby:stable

Thanks in advance,
MaDDoX

**Comment by abma** [comment]
done.

ps.: its gajop :-)

**Comment by MaDDoXbr** [comment]
Thanks!!

ps: Fixed, lol
