### ISSUE TITLE
Tech Annihilation

### ISSUE THREAD

**Issue by skymyj** [spring/RapidTools#71]
Hey. 
Atm, when I release a commit, there is no more new version added.
The issue appeared this weekend.

Is it normal ?

**Comment by skymyj** [comment]
https://github.com/techannihilation/TA

**Comment by abma** [comment]
the repository seems to be updated:

https://repos.springrts.com/techa/log.txt

versions.gz seems to contain the latest version, too:
https://repos.springrts.com/techa/versions.gz
->
techa:test,a7e87325f7e3278a087c4be41bffdaff,,Tech Annihilation test-10015-49014cf

49014cf is the latest version on https://github.com/techannihilation/TA

so, do you have more details? seems to be a problem at client side.

**Comment by skymyj** [comment]
Thanks for your answer. 
I will check on servers. 
Strange, because 2 differents servers not update the game.

**Comment by skymyj** [comment]
Atm, seems to work on 1 server. 
So I think the issue came from client for second server

**Comment by abma** [comment]
what is used to download / update the game(s)?

**Comment by abma** [comment]
do you have a log file / error message?

**Comment by jochumdev** [comment]
It my fault

**Comment by skymyj** [comment]
Hm. So it's ok. No more issue. 
Thank again abma
