### ISSUE TITLE
Add repository to rapid

### ISSUE THREAD

**Issue by tizbac** [spring/RapidTools#72]
Hi, can you add https://github.com/tizbac/fleaspam to rapid ?
For the tag tafs:latest is fine

**Comment by abma** [comment]
done

after the next commit to the repo the update log should update:

https://repos.springrts.com/tafs/log.txt

(with a delay of ~5 minutes)

**Comment by tizbac** [comment]
Tried to push to the repository but still no log.txt  (hours ago )

**Comment by abma** [comment]
rapid uses the "master" branch... there is only a single commit there.
